name: C CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**Makefile'
      - '**c_ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**Makefile'
      - '**c_ci.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make libs
      run: make libs
    - name: make
      run: make
