name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths: 
      - '**.c'
      - '**.h'
      - '**Makefile'
  pull_request:
    branches: [ master ]
    paths: 
      - '**.c'
      - '**.h'
      - '**Makefile'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make libs
      run: make libs
    - name: make
      run: make
    - name: check
      run: |
        pip install numpy
        make check
