name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**Makefile'
      - '**ccpp.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**Makefile'
      - '**ccpp.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make libs
      run: make libs
    - name: make
      run: make
    - name: make check
      run: |
        pip3 install numpy
        make check
